module.exports = function (repo) {
    return {
        id: repo.id,
        name: repo.name,
        full_name: repo.full_name,
        owner: {
            login: repo.owner.login,
            id: repo.owner.id,
            avatar_url: repo.owner.avatar_url,
            api_url: repo.owner.url,
            html_url: repo.owner.html_url,
            repos_url: repo.owner.repos_url,
            type: repo.owner.type,
            site_admin: repo.owner.site_admin
        },
        description: repo.description,
        private: repo.private,
        html_url: repo.html_url,
        forks_url: repo.forks_url,
        // collaborators_url: repo.collaborators_url,
        // teams, hooks, and issue events url?
        assignees_url: repo.assignees_url,
        // languages_url: repo.languages_url,
        // contributors_url: repo.contributors_url,
        // subscribers_url: repo.subscribers_url,
        commits_url: repo.commits_url,
        git_commits_url: repo.git_commits_url,
        // contents_url: repo.contents_url,
        // merges_url: repo.merges_url,
        // downloads_url: repo.downloads_url,
        // issues_url: repo.issues_url,
        // issue_comments_url: repo.issue_comments_url,
        // pulls_url: repo.pulls_url,
        labels_url: repo.labels_url,
        created_at: repo.created_at,
        updated_at: repo.updated_at,
        // pushed_at: repo.pushed_at,
        // git_url: repo.git_url,
        clone_url: repo.clone_url,
        homepage: repo.homepage,
        // size: repo.size,
        // language: repo.language,
        has_issues: repo.has_issues,
        open_issues: repo.open_issues,
        open_issues_count: repo.open_issues_count,
        default_branch: repo.default_branch,
        forks: repo.forks
    } 
}